### PR TITLE
repo name change from welcome to docs

### PR DESCRIPTION
**Pull request by ericpassmore**

### CODE REVIEW

**Comment by iamveritas** [comment]
there's also a function `Install_Welcome()` in the `install_welcome.sh` file

**Comment by lparisc** [comment]
> there's also a function `Install_Welcome()` in the `install_welcome.sh` file which must be renamed as well.

Non-breaking, but yeah should be renamed too.

**Review by lparisc — APPROVED** [review]

**Comment by ericpassmore** [comment]
> Non-breaking, but yeah should be renamed too.

Actually that is breaking, good find, difficult to test until the repo rename goes through

**Comment by lparisc** [comment]
> > Non-breaking, but yeah should be renamed too.
> 
> Actually that is breaking, good find, difficult to test until the repo rename goes through

Ahhh I see why now... yeah good find @iamveritas 
```
  COMMAND="Install_${GIT_BASE_REPO} ...
  $COMMAND
```

**Pull request merged**
